/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
2025-09-23 18:03:52,135 INFO     Starting server at tcp:port=8000:interface=127.0.0.1
2025-09-23 18:03:52,136 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2025-09-23 18:03:52,136 INFO     Configuring endpoint tcp:port=8000:interface=127.0.0.1
2025-09-23 18:03:52,138 INFO     Listening on TCP address 127.0.0.1:8000
INFO Request: HEAD /
INFO Response: 404 for HEAD /
INFO Request: HEAD /
ERROR Invalid HTTP_HOST header: 'api.ifap-edu.uk'. You may need to add 'api.ifap-edu.uk' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ifap-edu.uk'. You may need to add 'api.ifap-edu.uk' to ALLOWED_HOSTS.
INFO Response: 400 for HEAD /
INFO Request: POST /api/users/login/
INFO Response: 200 for POST /api/users/login/
INFO Request: GET /api/courses/my_courses/
INFO Request: GET /api/courses/
INFO User 10 requested course list
INFO Response: 200 for GET /api/courses/my_courses/
INFO Response: 200 for GET /api/courses/
INFO Request: GET /api/chat/notifications/
INFO Request: GET /api/courses/my_courses/
INFO Response: 200 for GET /api/chat/notifications/
INFO Request: GET /api/chat/notifications/
INFO Response: 200 for GET /api/chat/notifications/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Request: GET /api/courses/my_courses/
INFO Request: GET /api/users/role_summary/
INFO Response: 200 for GET /api/users/role_summary/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Request: GET /api/users/role_summary/
INFO Response: 200 for GET /api/users/role_summary/
INFO Request: GET /api/courses/my_courses/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Request: GET /api/courses/my_courses/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Request: GET /api/courses/taught_courses/
INFO Response: 200 for GET /api/courses/taught_courses/
INFO Request: GET /api/courses/taught_courses/
INFO Request: GET /api/courses/4/metrics/
INFO Response: 404 for GET /api/courses/4/metrics/
INFO Response: 200 for GET /api/courses/taught_courses/
INFO Request: GET /api/courses/3/metrics/
INFO Request: GET /api/courses/2/metrics/
INFO Response: 404 for GET /api/courses/2/metrics/
INFO Response: 404 for GET /api/courses/3/metrics/
INFO Request: GET /api/courses/1/metrics/
INFO Request: GET /api/courses/4/metrics/
INFO Response: 404 for GET /api/courses/1/metrics/
INFO Response: 404 for GET /api/courses/4/metrics/
INFO Request: GET /api/courses/3/metrics/
INFO Request: GET /api/courses/1/metrics/
INFO Request: GET /api/courses/2/metrics/
INFO Response: 404 for GET /api/courses/1/metrics/
INFO Response: 404 for GET /api/courses/3/metrics/
INFO Response: 404 for GET /api/courses/2/metrics/
2025-09-23 18:51:03,588 ERROR    Exception inside application: No route found for path 'ws/notifications/'.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/routing.py", line 150, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'ws/notifications/'.
INFO Request: GET /api/courses/my_courses/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Request: GET /api/courses/my_courses/
INFO Request: GET /api/users/role_summary/
INFO Response: 200 for GET /api/users/role_summary/
INFO Request: GET /api/users/role_summary/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Response: 200 for GET /api/users/role_summary/
2025-09-23 18:51:08,603 ERROR    Exception inside application: No route found for path 'ws/notifications/'.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/routing.py", line 150, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'ws/notifications/'.
2025-09-23 18:51:13,614 ERROR    Exception inside application: No route found for path 'ws/notifications/'.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/routing.py", line 150, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'ws/notifications/'.
2025-09-23 18:51:25,636 ERROR    Exception inside application: No route found for path 'ws/notifications/'.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/channels/routing.py", line 150, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'ws/notifications/'.
INFO Request: POST /api/users/logout/
INFO Response: 400 for POST /api/users/logout/
INFO Request: GET /
ERROR Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
INFO Response: 400 for GET /
INFO Request: GET /favicon.ico
ERROR Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
INFO Response: 400 for GET /favicon.ico
INFO Request: GET /favicon.png
ERROR Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
INFO Response: 400 for GET /favicon.png
INFO Request: GET /
ERROR Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
INFO Response: 400 for GET /
INFO Request: GET /favicon.ico
ERROR Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jorge/pagina web nueva ifap dos/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ifap-edu.uk'. You may need to add 'ifap-edu.uk' to ALLOWED_HOSTS.
INFO Response: 400 for GET /favicon.ico
INFO Request: POST /api/users/login/
INFO Response: 200 for POST /api/users/login/
INFO Request: GET /api/courses/
INFO Request: GET /api/courses/my_courses/
INFO User 10 requested course list
INFO Response: 200 for GET /api/courses/
INFO Request: GET /api/chat/notifications/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Request: GET /api/courses/my_courses/
INFO Response: 200 for GET /api/chat/notifications/
INFO Request: GET /api/chat/notifications/
INFO Response: 200 for GET /api/chat/notifications/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Request: GET /api/courses/my_courses/
INFO Request: GET /api/users/role_summary/
INFO Response: 200 for GET /api/users/role_summary/
INFO Request: GET /api/users/role_summary/
INFO Response: 200 for GET /api/courses/my_courses/
INFO Response: 200 for GET /api/users/role_summary/
INFO Request: POST /api/users/logout/
INFO Response: 400 for POST /api/users/logout/
INFO Request: GET /api/contact/info/
INFO Response: 404 for GET /api/contact/info/
INFO Request: GET /api/contact/info/
INFO Response: 404 for GET /api/contact/info/
